LAB_NAME="LinearTopology"

ha[0]="neta"
ha[image]="kathara/base"

r1[0]="neta"
r1[1]="netab"
r1[image]="kathara/frr"

r2[0]="netab"
r2[1]="netb"
r2[image]="kathara/frr"

hb[0]="netb"
hb[image]="kathara/base"