!
ip prefix-list BB2-RIP-TO-OSPF seq 10 permit 10.0.0.0/24
ip prefix-list BB2-RIP-TO-OSPF seq 20 permit 10.0.1.0/24
ip prefix-list BB2-RIP-TO-OSPF seq 30 permit 10.0.2.0/24
ip prefix-list BB2-RIP-TO-OSPF seq 40 permit 10.0.3.0/24
ip prefix-list BB2-RIP-TO-OSPF seq 50 permit 100.0.0.0/30
ip prefix-list BB2-RIP-TO-OSPF seq 60 permit 200.0.0.0/30
ip prefix-list BB2-RIP-TO-OSPF seq 70 permit 200.0.1.0/24
ip prefix-list BB2-OSPF-TO-RIP seq 10 permit 110.0.0.0/30
ip prefix-list BB2-OSPF-TO-RIP seq 20 permit 210.0.0.0/24
ip prefix-list BB2-OSPF-TO-RIP seq 30 permit 220.0.0.0/30
ip prefix-list BB2-OSPF-TO-RIP seq 40 permit 220.0.1.0/30
ip prefix-list BB2-OSPF-TO-RIP seq 50 permit 220.0.2.0/30
!
route-map BB2-RIP-TO-OSPF permit 10
 match ip address prefix-list BB2-RIP-TO-OSPF
!
route-map BB2-OSPF-TO-RIP permit 10
 match ip address prefix-list BB2-OSPF-TO-RIP
!
router ospf
 network 120.0.0.0/30 area 2.2.2.2
 network 130.0.0.0/30 area 3.3.3.3
 redistribute rip metric-type 2 metric 10 route-map BB2-RIP-TO-OSPF
!
router rip
 version 2
 network eth0
 network eth1
 redistribute connected metric 1
 redistribute ospf metric 2 route-map BB2-OSPF-TO-RIP
 no auto-summary
!
log file /var/log/frr/frr.log
