!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 300
 no bgp ebgp-requires-policy

 neighbor 4.4.4.20 remote-as 200
 neighbor 4.4.4.20 description Router r2 of AS200

 network 5.5.5.0/24