!
ip prefix-list BB1-RIP-TO-OSPF seq 10 permit 10.0.0.0/24
ip prefix-list BB1-RIP-TO-OSPF seq 20 permit 10.0.1.0/24
ip prefix-list BB1-RIP-TO-OSPF seq 30 permit 10.0.2.0/24
ip prefix-list BB1-RIP-TO-OSPF seq 40 permit 10.0.3.0/24
ip prefix-list BB1-RIP-TO-OSPF seq 50 permit 130.0.0.0/30
ip prefix-list BB1-RIP-TO-OSPF seq 60 permit 220.0.0.0/30
ip prefix-list BB1-RIP-TO-OSPF seq 70 permit 220.0.1.0/30
ip prefix-list BB1-RIP-TO-OSPF seq 80 permit 220.0.2.0/30
ip prefix-list BB1-OSPF-TO-RIP seq 10 permit 120.0.0.0/30
ip prefix-list BB1-OSPF-TO-RIP seq 20 permit 200.0.0.0/30
ip prefix-list BB1-OSPF-TO-RIP seq 30 permit 200.0.1.0/24
ip prefix-list BB1-OSPF-TO-RIP seq 40 permit 210.0.0.0/24
!
route-map BB1-RIP-TO-OSPF permit 10
 match ip address prefix-list BB1-RIP-TO-OSPF
!
route-map BB1-OSPF-TO-RIP permit 10
 match ip address prefix-list BB1-OSPF-TO-RIP
!
router ospf
 network 100.0.0.0/30 area 1.1.1.1
 network 110.0.0.0/30 area 2.2.2.2
 redistribute rip metric-type 2 metric 10 route-map BB1-RIP-TO-OSPF
!
router rip
 version 2
 network eth0
 network eth1
 redistribute connected metric 1
 redistribute ospf metric 2 route-map BB1-OSPF-TO-RIP
 no auto-summary
!
log file /var/log/frr/frr.log
