!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
router bgp 65001
 no bgp ebgp-requires-policy

 neighbor 198.51.100.1 remote-as 65003
 neighbor 198.51.100.1 description Customer-AS65003

 neighbor 203.0.113.2 remote-as 65004
 neighbor 203.0.113.2 description Internet-AS65004
!