!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!

router rip
 network 10.1.1.0/24
 redistribute bgp
!

route-map PREPEND-ISP1 permit 10
 set as-path prepend 65003 65003
!

route-map PREFER-ISP2 permit 10
 set local-preference 200
!

router bgp 65003
 no bgp ebgp-requires-policy

 network 172.16.1.0/24

 neighbor 198.51.100.2 remote-as 65001
 neighbor 198.51.100.2 description ISP1
 neighbor 198.51.100.2 route-map PREPEND-ISP1 out

 neighbor 198.51.100.6 remote-as 65002
 neighbor 198.51.100.6 description ISP2
 neighbor 198.51.100.6 route-map PREFER-ISP2 in
!