bb0[0]="A"
bb0[1]="B"
bb0[image]="kathara/base"

bb1[0]="A"
bb1[1]="B"
bb1[image]="kathara/base"

bb2[0]="A"
bb2[1]="B"
bb2[image]="kathara/base"

bb3[0]="A"
bb3[1]="B"
bb3[image]="kathara/base"

bb4[0]="A"
bb4[1]="B"
bb4[image]="kathara/base"