!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
router bgp 65002
 no bgp ebgp-requires-policy

 neighbor 198.51.100.5 remote-as 65003
 neighbor 198.51.100.5 description Customer-AS65003

 neighbor 203.0.113.5 remote-as 65004
 neighbor 203.0.113.5 description Internet-AS65004
!