!
! FRRouting configuration file
!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
debug bgp keepalives
debug bgp updates in
debug bgp updates out
!
router bgp 400
 no bgp ebgp-requires-policy

 neighbor 8.8.8.10 remote-as 100
 neighbor 8.8.8.10 description Router r1 of AS100

 neighbor 6.6.6.30 remote-as 300
 neighbor 6.6.6.30 description Router r3 of AS300

 network 7.7.7.0/24