!
password zebra
enable password zebra
!
log file /var/log/frr/frr.log
!
router bgp 65004
 no bgp ebgp-requires-policy
 bgp bestpath compare-routerid

 network 200.0.1.0/24

 neighbor 203.0.113.1 remote-as 65001
 neighbor 203.0.113.1 description ISP1

 neighbor 203.0.113.6 remote-as 65002
 neighbor 203.0.113.6 description ISP2
!